/*
    (c) 2020 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
*/

#ifndef CAN_TP_CONFIG_H
#define CAN_TP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
    
    /* Defined in the specification as TX_DL. Valid options are:
 *  8 = CAN Classic only
 *  12, 16, 20, 24, 32, 48, or 64 = CAN-FD only */
#define CAN_TP_TRANSMISSION_DATA_LENGTH_MAX 64
    
#define CAN_TP_MESSAGE_ID_IS_EXTENDED  false
#define CAN_TP_MESSAGE_ID_DATA         0xA2
#define CAN_TP_MESSAGE_ID_FLOW_CONTROL 0xA2
#define CAN_TP_DEFAULT_SEPARATION_TIME_MS 1
#define CAN_TP_DEFAULT_BLOCK_SIZE 0
    
#define CAN_TP_PAUSE_ON_FIRST_FRAME false

#ifdef __cplusplus
}
#endif

#endif /* CAN_TP_CONFIG_H */

